name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    concurrency:
      group: "test-${{ github.ref_name }}-${{ github.event.pull_request.number }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/cache@v3
        name: pnpm cache
        with:
          path: ${{ env.PNPM_HOME }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/.npmrc') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile
      - run: pnpm test.lint
      - run: pnpm test.types
      - run: pnpm test.vitest
      - run: pnpm plx playwright install # required for storybook testing
      - run: pnpm test.storybook
